ENH: Read the mask and set values to NaN
theroggy/cropclassification pull request #132
Opened 2024-08-21 07:18 UTC by KriWay-LV

2024-08-21 08:08 UTC, theroggy requested changes
Nice! Just some small details in the test code...

2024-08-21 08:08 UTC, theroggy commented on tests/test_raster_index_util.py
> +        src.descriptions = bands
Best move setting the band names to `create_gdal_raster`, and put the band names needed in an extra mark.parametrize parameter?

2024-08-21 11:25 UTC, KriWay-LV reviewed
> Best move setting the band names to `create_gdal_raster`, and put the band names needed in an extra mark.parametrize parameter? 

Not sure if this changes is correct ... rasterband.WriteArray(values)

2024-08-21 13:10 UTC, theroggy requested changes
Some new remarks...

2024-08-21 13:10 UTC, theroggy commented on tests/test_raster_index_util.py
> +        for i in range(bands):
An `if offset:` is missing here...

2024-08-21 13:10 UTC, theroggy commented on tests/test_raster_index_util.py
> +    bands=None,
```suggestion
    band_descriptions=None,
```
Is probably a clearer name?

2024-08-21 13:10 UTC, theroggy commented on tests/test_raster_index_util.py
> +            rasterband.WriteArray(values)
It is slightly odd that the same data is always written to all bands... Works for this specific test, but doesn't scale very well to be able to use the function for other tests? Was this the way it worked in the original function as well?

2024-08-21 13:10 UTC, theroggy commented on tests/test_raster_index_util.py
> +        src.descriptions = bands
This code has become obsolete?

2024-08-22 09:20 UTC, theroggy requested changes
Almost there :-)

2024-08-22 09:20 UTC, theroggy commented on tests/test_raster_index_util.py
> +            ds.GetRasterBand(i + 1).SetOffset(offset)
The loop should be in a range of the number of bands based on the dimensions of the "values" array like before.

2024-08-22 09:20 UTC, theroggy commented on tests/test_raster_index_util.py
> +        bands=len(band_descriptions),
Should be the number of bands determined based on the dimensions of the "values" array like before. Otherwise it just crashes e.g. if there are no band_descriptions specified.

2024-08-23 06:43 UTC, merged