ENH: Add support for spatial aggregation arguments to exactextract
theroggy/cropclassification pull request #159
Opened 2024-10-02 09:12 UTC by KriWay-LV

2024-10-11 12:44 UTC, theroggy requested changes

2024-10-11 12:44 UTC, theroggy commented on cropclassification/util/zonal_stats_bulk/__init__.py
> +                "spatial_aggregation_args": conf.timeseries.getdict(
The "conf" object should not be accessed in the util modules... The configuration is one way to use cropclassification, but there are scenario's where using it directly via the API rather than via confiruration in general, and especially the util modules are meant to be reusable. Same as in orthoseg.

At first sight I would keep the API as it is and just keep stats a list[str] with for exactextract possibly values like this:
``` python
    [
        "count(min_coverage_frac=0.5,coverage_weight=none)",
        "mean(min_coverage_frac=0.5,coverage_weight=none)",
        "median(min_coverage_frac=0.5,coverage_weight=none)",
    ]
```

This way at the lower level API's at least we keep all options open to have e.g. different arguments per aggregation...

2024-10-11 12:44 UTC, theroggy commented on tests/test_zonal_stats_bulk.py
> +    assert len(ops) == 6
Best test on the actual values being returned rather than just the number of returned elements...

2024-10-14 06:52 UTC, KriWay-LV commented on tests/test_zonal_stats_bulk.py
> +    assert len(ops) == 6
Function no longer needed, so test is removed

2025-02-10 20:19 UTC, theroggy approved these changes

2025-02-10 20:57 UTC, merged