ENH: Script to automate periodic download of images
theroggy/cropclassification pull request #68
Opened 2024-03-25 06:48 UTC by KriWay

- add task and test periodic download

2024-03-26 19:38 UTC, theroggy requested changes
Your `if not simulate:` check made me wonder, maybe this principle can be used to make to move the script to make it a real test anyway?

2024-03-28 10:00 UTC, theroggy requested changes
Looks great.

Just one small remark...

2024-03-28 10:00 UTC, theroggy commented on cropclassification/general.ini
> +simulate = MUST_OVERRIDE
```suggestion
simulate = False
```
I think it is more logical to use False as default here?

It is typically only for testing purposes that simulate is relevant?

2024-03-28 11:59 UTC, KriWay commented on cropclassification/general.ini
> +simulate = MUST_OVERRIDE
yes indeed

2024-03-28 15:03 UTC, theroggy approved these changes
Nice, ready to go!

2024-03-28 15:03 UTC, merged